services:
  client-stage:
    profiles: ["stage"]
    image: tourgo-client:stage
    build:
      context: .
      dockerfile: Dockerfile.stage
    container_name: react-staging-app
    restart: always
    ports:
      - "3001:80"
    
  client-prod:
    profiles: ["prod"]
    image: tourgo-client:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: react-prod-app
    restart: always
    ports:
      - "3002:80"